version: '3'

services:
  tetris:
    container_name:  ${CON_NAME} #tetris-container
    build:
      context: .
      dockerfile: ./docker/Dockerfile.latest
    volumes:
      - type: bind
        source: .
        target: /tetris
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - type: bind
        source: /etc/group
        target: /etc/group
      - type: bind
        source: /etc/passwd
        target: /etc/passwd
      - type: bind
        source: /etc/shadow
        target: /etc/shadow
      - type: bind
        source: /etc/sudoers.d
        target: /etc/sudoers.d
    environment:
    # - DISPLAY==localhost$DISPLAY #host.docker.internal:0.0
    # Display X Server GUI.
    - DISPLAY=${DISPLAY}
    - QT_X11_NO_MITSHM=1
    - LIBGL_ALWAYS_INDIRECT=1
    # WSLg
    # - DISPLAY=$DISPLAY
    - XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
    # GPUを使うための設定
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all
    tty: true
    shm_size: 512m
